apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-clusterip
  namespace: petclinic
spec:
  type: ClusterIP
  selector:
    app: petclinic
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080